### ISSUE TITLE
Unit test exercise - completed function

### ISSUE THREAD

**Issue by Kirit-Singh** [Kirit-Singh/BME547_Classwork_Spring2023#14]
Completed function for unit test
[xy_calculator](https://github.com/Kirit-Singh/BME547_Classwork_Spring2023/blob/unit_testing_exercise/xy_calculator.py)

**Comment by dward2** [comment]
In this file, you have a `test_line_checker` function.  Unit test functions should be in a separate module.  I do see that you did create a separate file and have a version of `test_line_checker()` in your `test_xy_calculator.py` module, which is where it should be.  So, for clarity, in the future, I would not have versions of test functions in the module with the code to be tested.

**Comment by Kirit-Singh** [comment]
I've removed test_line_checker from xy_calculator
